-- TEST BASE
SELECT COUNT(*) FROM venta;

-- PERFORMANCE
EXPLAIN (ANALYZE, BUFFERS)
SELECT *
FROM venta
WHERE fecha_venta >= NOW() - INTERVAL '30 days';

-- FORZAR SIN INDEX
SET enable_indexscan = off;

EXPLAIN (ANALYZE, BUFFERS)
SELECT *
FROM venta
WHERE fecha_venta >= NOW() - INTERVAL '30 days';

-- FORZAR CON INDEX
SET enable_seqscan = off;

EXPLAIN (ANALYZE, BUFFERS)
SELECT *
FROM venta
WHERE fecha_venta >= NOW() - INTERVAL '30 days';

-- DALIBO JSON
EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON)
SELECT *
FROM venta
WHERE fecha_venta >= NOW() - INTERVAL '30 days';

-- CASOS
EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON)
SELECT * FROM venta WHERE cliente_id = 50000;

EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON)
SELECT * FROM venta_linea WHERE sku_id = 1000;